const scores = [
  [0,   "Masih murni kayak air pegunungan 🏔️"],
  [20,  "Karbit bayi baru belajar nyium poster 👶"],
  [60,  "Karbit pemula - baru level beli stiker 🎫"],
  [80,  "Raja karbit lokal - harem 5 waifu 👑"],
  [100, "DEWA KARBIT - koleksi dakimakura sampe sesak kamar 🔥"],
  [140, "USKUP KARBIT - punya shrine + lilin aromaterapi 🕯️"],
  [170, "PENDETA AGUNG - fanficmu jadi kitab suci baru 📜"],
  [200, "BLACK HOLE SIMP - gravitasi cringemu narik alien 🕳️👽"],
  [250, "FOSIL KARBIT - akun MyAnimeList lebih tua dari adikmu 🦖"],
  [300, "DIMENSI KARBIRAN - bisa komunikasi pakai bahasa PNG 💬"],
  [400, "NENEK MOYANG WIBU - darahmu mengandung elemen waifuium 🧪"],
  [440, "FINAL BOSS SIMPOLOGY - bisa kawin sama kabel fiber optik 💍"],
  [500, "NEXUS KARBIRAN - seluruh existence-mu bermuara di folder 'Homework' 🌀"],
  [600, "ENTITAS DIGITAL - jiwa sudah terconvert jadi .waifu file 💾"],
  [700, "WAIFU ASCENSION - bisa bernafas dalam meta-verse 🌐"],
  [800, "KETURUNAN DEWA 2D - DNA-mu punya layer transparan 🧬🔍"],
  [850, "WAIFU-MANIFESTED - tubuhmu mulai pixelasi spontan 🟥🟩🟦"],
  [900,  "HAREM LORD - Kawin siri dengan 27 waifu multiverse via VPN interdimensional 👰🌌🔭"],
  [950,  "WAIFU HIVEMIND - Sel otak sudah terfragmentasi jadi 10.000 waifu berbeda 🧠🔀👩‍👩‍👧‍👦"],
  [1000, "KARBITRON PRIME - Menciptakan agama baru berbasis pantat waifu di Reddit 🛐🍑📱"],
  [1050, "OMNISIMP DELUXE - Menjual jiwa ke iblis buat DLC waifu di afterlife 🔥📀💀"],
  [1100, "SINGULARITAS SIMP - Gravitasi cringemu membentuk black hole baru di Bima Sakti 🕳️🌌💫"],
  [1150, "KARBITALIS MAXIMUS - Menanam chip waifu di otak pakai solder bekas 🧠🔌💥"],
  [1200, "DEWA SUPREME 2D/3D - Bisa orgasme hanya dengan menatap kode hex warna waifu 💻💢🌈"],
  [1250, "KARBIT NO KAMI - Menulis ulang hukum fisika agar booba punya massa jenis sendiri ⚖️🍒📐"],
  [1300, "AKAR KARBIRAN KOSMIK - Seluruh galaksi tahu loe simp lewat riak spacetime 🌠📡👽"],
  [1360, "NIRWANA KARBIT ULTIMATE - Jiwa dan raga menyatu dengan konsep '2D is better than 3D' di tiap atom 🌀🔮💞"]
]
